### ISSUE TITLE
questions regarding temp_sensor & z_stepper configurations

### ISSUE THREAD

**Issue by dukeduck1984** [alchemyEngine/klipper_frame_expansion_comp#1]
Hi,

My chamber temp sensor was already defined in [temperature_fan] section as the chamber fan was controlled by this thermsitor, I cannot use it to define in a [temperature_sensor] section otherwise an error would be raised.  How can I deal with this issue?  Any work around?

Also, how to configure the z_stepper for voron2.4 since there're 4 z steppers?

Thanks.

**Comment by alchemyEngine** [comment]
Hi @dukeduck1984,

You can simply use your temperature_fan config name as the `temp_sensor` parameter in the `[frame_expansion_compensation]` config and everything will function as intended. E.g: `temp_sensor: temperature_fan exhaust_fan`.

In the Voron 2.4 config, `[stepper_z]` is the stepper through which the endstop is configured therefore use `stepper_z` there.

Best,
-alch3my
