### ISSUE TITLE
Bug?  - Since installing klicky I get a shutdown error on homing sometimes now. - Frame comp issue?

### ISSUE THREAD

**Issue by PhilBaz** [alchemyEngine/klipper_frame_expansion_comp#6]
Please see here

https://github.com/jlas1/Klicky-Probe/issues/148#issuecomment-1247142557

**Comment by alchemyEngine** [comment]
Try it with the latest commit

**Comment by PhilBaz** [comment]
@alchemyEngine 

Soon as I get a chance. The error has only happened a couple times in the last day or two and the printer is still functional. I got something in there right now. 

Ill update through moonraker

**Comment by PhilBaz** [comment]
@alchemyEngine Its not coming up as an update in mainsail. Do I need to go manual?

**Comment by PhilBaz** [comment]
@alchemyEngine Okay, in the mainsail update came through. Ill report back if it happens again. Or close the issue if it doesnt.

Thank you! Frame comp and VGB have fixed all my thermal problems :)

**Comment by PhilBaz** [comment]
Hasn't happened since the update...
