### ISSUE TITLE
QUERY_FRAME_COMP in klipper implementation...

### ISSUE THREAD

**Issue by PhilBaz** [alchemyEngine/klipper_frame_expansion_comp#7]
The new klipper documentation doesn't say anything about a query function.... will it still work? If not any reason I shouldn't just stay with the plugin?

**Comment by alchemyEngine** [comment]
Using SET_Z_THERMAL_ADJUST without any parameters provides the query
functionality now. It's in line with other klipper commands line
SET_VELOCITY_LIMIT, etc

**Comment by PhilBaz** [comment]
Thanks!

**Comment by PhilBaz** [comment]
Sorry, one question....Under the new implementation is there a way to have the temp show in the temperatures in mainsail?  I no longer get a temp line for it. 

Its important to keep track of whether the frame is heating or cooling between prints.

**Comment by alchemyEngine** [comment]
Unfortunately this will need to be implemented on the front-end side. A FR
to Mainsail/Fluidd would help.

**Comment by PhilBaz** [comment]
Ahh, okay. Ill put those in. ill just use the plugin till they get implemented.

Thanks!

**Comment by alchemyEngine** [comment]
FYI you can still see the frame temperature line on the Mainsail graph,
just not in sensor readout panel. Mouse over to see it.

**Comment by PhilBaz** [comment]
@alchemyEngine 

Ahh, okay... good to know!
